export const CountryData = [
  {
    label: 'Afghanistan',
    dial_value: '+93',
    emoji: '🇦🇫',
    value: 'AF',
  },
  {
    label: 'Aland Islands',
    dial_value: '+358',
    emoji: '🇦🇽',
    value: 'AX',
  },
  {
    label: 'Albania',
    dial_value: '+355',
    emoji: '🇦🇱',
    value: 'AL',
  },
  {
    label: 'Algeria',
    dial_value: '+213',
    emoji: '🇩🇿',
    value: 'DZ',
  },
  {
    label: 'American Samoa',
    dial_value: '+1684',
    emoji: '🇦🇸',
    value: 'AS',
  },
  {
    label: 'Andorra',
    dial_value: '+376',
    emoji: '🇦🇩',
    value: 'AD',
  },
  {
    label: 'Angola',
    dial_value: '+244',
    emoji: '🇦🇴',
    value: 'AO',
  },
  {
    label: 'Anguilla',
    dial_value: '+1264',
    emoji: '🇦🇮',
    value: 'AI',
  },
  {
    label: 'Antarctica',
    dial_value: '+672',
    emoji: '🇦🇶',
    value: 'AQ',
  },
  {
    label: 'Antigua & Barbuda',
    dial_value: '+1268',
    emoji: '🇦🇬',
    value: 'AG',
  },
  {
    label: 'Argentina',
    dial_value: '+54',
    emoji: '🇦🇷',
    value: 'AR',
  },
  {
    label: 'Armenia',
    dial_value: '+374',
    emoji: '🇦🇲',
    value: 'AM',
  },
  {
    label: 'Aruba',
    dial_value: '+297',
    emoji: '🇦🇼',
    value: 'AW',
  },
  {
    label: 'Australia',
    dial_value: '+61',
    emoji: '🇦🇺',
    value: 'AU',
  },
  {
    label: 'Austria',
    dial_value: '+43',
    emoji: '🇦🇹',
    value: 'AT',
  },
  {
    label: 'Azerbaijan',
    dial_value: '+994',
    emoji: '🇦🇿',
    value: 'AZ',
  },
  {
    label: 'Bahamas',
    dial_value: '+1242',
    emoji: '🇧🇸',
    value: 'BS',
  },
  {
    label: 'Bahrain',
    dial_value: '+973',
    emoji: '🇧🇭',
    value: 'BH',
  },
  {
    label: 'Bangladesh',
    dial_value: '+880',
    emoji: '🇧🇩',
    value: 'BD',
  },
  {
    label: 'Barbados',
    dial_value: '+1246',
    emoji: '🇧🇧',
    value: 'BB',
  },
  {
    label: 'Belarus',
    dial_value: '+375',
    emoji: '🇧🇾',
    value: 'BY',
  },
  {
    label: 'Belgium',
    dial_value: '+32',
    emoji: '🇧🇪',
    value: 'BE',
  },
  {
    label: 'Belize',
    dial_value: '+501',
    emoji: '🇧🇿',
    value: 'BZ',
  },
  {
    label: 'Benin',
    dial_value: '+229',
    emoji: '🇧🇯',
    value: 'BJ',
  },
  {
    label: 'Bermuda',
    dial_value: '+1441',
    emoji: '🇧🇲',
    value: 'BM',
  },
  {
    label: 'Bhutan',
    dial_value: '+975',
    emoji: '🇧🇹',
    value: 'BT',
  },
  {
    label: 'Bolivia',
    dial_value: '+591',
    emoji: '🇧🇴',
    value: 'BO',
  },
  {
    label: 'Bosnia & Herzegovina',
    dial_value: '+387',
    emoji: '🇧🇦',
    value: 'BA',
  },
  {
    label: 'Botswana',
    dial_value: '+267',
    emoji: '🇧🇼',
    value: 'BW',
  },
  {
    label: 'Brazil',
    dial_value: '+55',
    emoji: '🇧🇷',
    value: 'BR',
  },
  {
    label: 'British Indian Ocean Territory',
    dial_value: '+246',
    emoji: '🇮🇴',
    value: 'IO',
  },
  {
    label: 'Brunei Darussalam',
    dial_value: '+673',
    emoji: '🇧🇳',
    value: 'BN',
  },
  {
    label: 'Bulgaria',
    dial_value: '+359',
    emoji: '🇧🇬',
    value: 'BG',
  },
  {
    label: 'Burkina Faso',
    dial_value: '+226',
    emoji: '🇧🇫',
    value: 'BF',
  },
  {
    label: 'Burundi',
    dial_value: '+257',
    emoji: '🇧🇮',
    value: 'BI',
  },
  {
    label: 'Cambodia',
    dial_value: '+855',
    emoji: '🇰🇭',
    value: 'KH',
  },
  {
    label: 'Cameroon',
    dial_value: '+237',
    emoji: '🇨🇲',
    value: 'CM',
  },
  {
    label: 'Canada',
    dial_value: '+1',
    emoji: '🇨🇦',
    value: 'CA',
  },
  {
    label: 'Cape Verde',
    dial_value: '+238',
    emoji: '🇨🇻',
    value: 'CV',
  },
  {
    label: 'Cayman Islands',
    dial_value: '+345',
    emoji: '🇰🇾',
    value: 'KY',
  },
  {
    label: 'Central African Republic',
    dial_value: '+236',
    emoji: '🇨🇫',
    value: 'CF',
  },
  {
    label: 'Chad',
    dial_value: '+235',
    emoji: '🇹🇩',
    value: 'TD',
  },
  {
    label: 'Chile',
    dial_value: '+56',
    emoji: '🇨🇱',
    value: 'CL',
  },
  {
    label: 'China',
    dial_value: '+86',
    emoji: '🇨🇳',
    value: 'CN',
  },
  {
    label: 'Christmas Island',
    dial_value: '+61',
    emoji: '🇨🇽',
    value: 'CX',
  },
  {
    label: 'Cocos (Keeling) Islands',
    dial_value: '+61',
    emoji: '🇨🇨',
    value: 'CC',
  },
  {
    label: 'Colombia',
    dial_value: '+57',
    emoji: '🇨🇴',
    value: 'CO',
  },
  {
    label: 'Comoros',
    dial_value: '+269',
    emoji: '🇰🇲',
    value: 'KM',
  },
  {
    label: 'Congo - Brazzaville',
    dial_value: '+242',
    emoji: '🇨🇬',
    value: 'CG',
  },
  {
    label: 'Congo - Kinshasa',
    dial_value: '+243',
    emoji: '🇨🇩',
    value: 'CD',
  },
  {
    label: 'Cook Islands',
    dial_value: '+682',
    emoji: '🇨🇰',
    value: 'CK',
  },
  {
    label: 'Costa Rica',
    dial_value: '+506',
    emoji: '🇨🇷',
    value: 'CR',
  },
  {
    label: "Cote d'Ivoire",
    dial_value: '+225',
    emoji: '🇨🇮',
    value: 'CI',
  },
  {
    label: 'Croatia',
    dial_value: '+385',
    emoji: '🇭🇷',
    value: 'HR',
  },
  {
    label: 'Cuba',
    dial_value: '+53',
    emoji: '🇨🇺',
    value: 'CU',
  },
  {
    label: 'Cyprus',
    dial_value: '+357',
    emoji: '🇨🇾',
    value: 'CY',
  },
  {
    label: 'Czech Republic',
    dial_value: '+420',
    emoji: '🇨🇿',
    value: 'CZ',
  },
  {
    label: 'Denmark',
    dial_value: '+45',
    emoji: '🇩🇰',
    value: 'DK',
  },
  {
    label: 'Djibouti',
    dial_value: '+253',
    emoji: '🇩🇯',
    value: 'DJ',
  },
  {
    label: 'Dominica',
    dial_value: '+1767',
    emoji: '🇩🇲',
    value: 'DM',
  },
  {
    label: 'Dominican Republic',
    dial_value: '+1849',
    emoji: '🇩🇴',
    value: 'DO',
  },
  {
    label: 'Ecuador',
    dial_value: '+593',
    emoji: '🇪🇨',
    value: 'EC',
  },
  {
    label: 'Egypt',
    dial_value: '+20',
    emoji: '🇪🇬',
    value: 'EG',
  },
  {
    label: 'El Salvador',
    dial_value: '+503',
    emoji: '🇸🇻',
    value: 'SV',
  },
  {
    label: 'Equatorial Guinea',
    dial_value: '+240',
    emoji: '🇬🇶',
    value: 'GQ',
  },
  {
    label: 'Eritrea',
    dial_value: '+291',
    emoji: '🇪🇷',
    value: 'ER',
  },
  {
    label: 'Estonia',
    dial_value: '+372',
    emoji: '🇪🇪',
    value: 'EE',
  },
  {
    label: 'Ethiopia',
    dial_value: '+251',
    emoji: '🇪🇹',
    value: 'ET',
  },
  {
    label: 'Falkland Islands (Malvinas)',
    dial_value: '+500',
    emoji: '🇫🇰',
    value: 'FK',
  },
  {
    label: 'Faroe Islands',
    dial_value: '+298',
    emoji: '🇫🇴',
    value: 'FO',
  },
  {
    label: 'Fiji',
    dial_value: '+679',
    emoji: '🇫🇯',
    value: 'FJ',
  },
  {
    label: 'Finland',
    dial_value: '+358',
    emoji: '🇫🇮',
    value: 'FI',
  },
  {
    label: 'France',
    dial_value: '+33',
    emoji: '🇫🇷',
    value: 'FR',
  },
  {
    label: 'French Guiana',
    dial_value: '+594',
    emoji: '🇬🇫',
    value: 'GF',
  },
  {
    label: 'French Polynesia',
    dial_value: '+689',
    emoji: '🇵🇫',
    value: 'PF',
  },
  {
    label: 'Gabon',
    dial_value: '+241',
    emoji: '🇬🇦',
    value: 'GA',
  },
  {
    label: 'Gambia',
    dial_value: '+220',
    emoji: '🇬🇲',
    value: 'GM',
  },
  {
    label: 'Georgia',
    dial_value: '+995',
    emoji: '🇬🇪',
    value: 'GE',
  },
  {
    label: 'Germany',
    dial_value: '+49',
    emoji: '🇩🇪',
    value: 'DE',
  },
  {
    label: 'Ghana',
    dial_value: '+233',
    emoji: '🇬🇭',
    value: 'GH',
  },
  {
    label: 'Gibraltar',
    dial_value: '+350',
    emoji: '🇬🇮',
    value: 'GI',
  },
  {
    label: 'Greece',
    dial_value: '+30',
    emoji: '🇬🇷',
    value: 'GR',
  },
  {
    label: 'Greenland',
    dial_value: '+299',
    emoji: '🇬🇱',
    value: 'GL',
  },
  {
    label: 'Grenada',
    dial_value: '+1473',
    emoji: '🇬🇩',
    value: 'GD',
  },
  {
    label: 'Guadeloupe',
    dial_value: '+590',
    emoji: '🇬🇵',
    value: 'GP',
  },
  {
    label: 'Guam',
    dial_value: '+1671',
    emoji: '🇬🇺',
    value: 'GU',
  },
  {
    label: 'Guatemala',
    dial_value: '+502',
    emoji: '🇬🇹',
    value: 'GT',
  },
  {
    label: 'Guernsey',
    dial_value: '+44',
    emoji: '🇬🇬',
    value: 'GG',
  },
  {
    label: 'Guinea',
    dial_value: '+224',
    emoji: '🇬🇳',
    value: 'GN',
  },
  {
    label: 'Guinea-Bissau',
    dial_value: '+245',
    emoji: '🇬🇼',
    value: 'GW',
  },
  {
    label: 'Guyana',
    dial_value: '+595',
    emoji: '🇬🇾',
    value: 'GY',
  },
  {
    label: 'Haiti',
    dial_value: '+509',
    emoji: '🇭🇹',
    value: 'HT',
  },
  {
    label: 'Holy See (Vatican City State)',
    dial_value: '+379',
    emoji: '🇻🇦',
    value: 'VA',
  },
  {
    label: 'Honduras',
    dial_value: '+504',
    emoji: '🇭🇳',
    value: 'HN',
  },
  {
    label: 'Hong Kong',
    dial_value: '+852',
    emoji: '🇭🇰',
    value: 'HK',
  },
  {
    label: 'Hungary',
    dial_value: '+36',
    emoji: '🇭🇺',
    value: 'HU',
  },
  {
    label: 'Iceland',
    dial_value: '+354',
    emoji: '🇮🇸',
    value: 'IS',
  },
  {
    label: 'India',
    dial_value: '+91',
    emoji: '🇮🇳',
    value: 'IN',
  },
  {
    label: 'Indonesia',
    dial_value: '+62',
    emoji: '🇮🇩',
    value: 'ID',
  },
  {
    label: 'Iran',
    dial_value: '+98',
    emoji: '🇮🇷',
    value: 'IR',
  },
  {
    label: 'Iraq',
    dial_value: '+964',
    emoji: '🇮🇷',
    value: 'IQ',
  },
  {
    label: 'Ireland',
    dial_value: '+353',
    emoji: '🇮🇪',
    value: 'IE',
  },
  {
    label: 'Isle of Man',
    dial_value: '+44',
    emoji: '🇮🇲',
    value: 'IM',
  },
  {
    label: 'Israel',
    dial_value: '+972',
    emoji: '🇮🇱',
    value: 'IL',
  },
  {
    label: 'Italy',
    dial_value: '+39',
    emoji: '🇮🇹',
    value: 'IT',
  },
  {
    label: 'Jamaica',
    dial_value: '+1876',
    emoji: '🇯🇲',
    value: 'JM',
  },
  {
    label: 'Japan',
    dial_value: '+81',
    emoji: '🇯🇵',
    value: 'JP',
  },
  {
    label: 'Jersey',
    dial_value: '+44',
    emoji: '🇯🇪',
    value: 'JE',
  },
  {
    label: 'Jordan',
    dial_value: '+962',
    emoji: '🇯🇴',
    value: 'JO',
  },
  {
    label: 'Kazakhstan',
    dial_value: '+77',
    emoji: '🇰🇿',
    value: 'KZ',
  },
  {
    label: 'Kenya',
    dial_value: '+254',
    emoji: '🇰🇪',
    value: 'KE',
  },
  {
    label: 'Kiribati',
    dial_value: '+686',
    emoji: '🇰🇮',
    value: 'KI',
  },
  {
    label: 'Korea (North)',
    dial_value: '+850',
    emoji: '🇰🇵',
    value: 'KP',
  },
  {
    label: 'Korea (South)',
    dial_value: '+82',
    emoji: '🇰🇷',
    value: 'KR',
  },
  {
    label: 'Kuwait',
    dial_value: '+965',
    emoji: '🇰🇼',
    value: 'KW',
  },
  {
    label: 'Kyrgyzstan',
    dial_value: '+996',
    emoji: '🇰🇬',
    value: 'KG',
  },
  {
    label: 'Laos',
    dial_value: '+856',
    emoji: '🇱🇦',
    value: 'LA',
  },
  {
    label: 'Latvia',
    dial_value: '+371',
    emoji: '🇱🇻',
    value: 'LV',
  },
  {
    label: 'Lebanon',
    dial_value: '+961',
    emoji: '🇱🇧',
    value: 'LB',
  },
  {
    label: 'Lesotho',
    dial_value: '+266',
    emoji: '🇱🇸',
    value: 'LS',
  },
  {
    label: 'Liberia',
    dial_value: '+231',
    emoji: '🇱🇷',
    value: 'LR',
  },
  {
    label: 'Libyan Arab Jamahiriya',
    dial_value: '+218',
    emoji: '🇱🇾',
    value: 'LY',
  },
  {
    label: 'Liechtenstein',
    dial_value: '+423',
    emoji: '🇱🇮',
    value: 'LI',
  },
  {
    label: 'Lithuania',
    dial_value: '+370',
    emoji: '🇱🇹',
    value: 'LT',
  },
  {
    label: 'Luxembourg',
    dial_value: '+352',
    emoji: '🇱🇺',
    value: 'LU',
  },
  {
    label: 'Macao',
    dial_value: '+853',
    emoji: '🇲🇴',
    value: 'MO',
  },
  {
    label: 'Macedonia',
    dial_value: '+389',
    emoji: '🇲🇰',
    value: 'MK',
  },
  {
    label: 'Madagascar',
    dial_value: '+261',
    emoji: '🇲🇬',
    value: 'MG',
  },
  {
    label: 'Malawi',
    dial_value: '+265',
    emoji: '🇲🇼',
    value: 'MW',
  },
  {
    label: 'Malaysia',
    dial_value: '+60',
    emoji: '🇲🇾',
    value: 'MY',
  },
  {
    label: 'Maldives',
    dial_value: '+960',
    emoji: '🇲🇻',
    value: 'MV',
  },
  {
    label: 'Mali',
    dial_value: '+223',
    emoji: '🇲🇱',
    value: 'ML',
  },
  {
    label: 'Malta',
    dial_value: '+356',
    emoji: '🇲🇹',
    value: 'MT',
  },
  {
    label: 'Marshall Islands',
    dial_value: '+692',
    emoji: '🇲🇭',
    value: 'MH',
  },
  {
    label: 'Martinique',
    dial_value: '+596',
    emoji: '🇲🇶',
    value: 'MQ',
  },
  {
    label: 'Mauritania',
    dial_value: '+222',
    emoji: '🇲🇷',
    value: 'MR',
  },
  {
    label: 'Mauritius',
    dial_value: '+230',
    emoji: '🇲🇺',
    value: 'MU',
  },
  {
    label: 'Mayotte',
    dial_value: '+262',
    emoji: '🇾🇹',
    value: 'YT',
  },
  {
    label: 'Mexico',
    dial_value: '+52',
    emoji: '🇲🇽',
    value: 'MX',
  },
  {
    label: 'Micronesia',
    dial_value: '+691',
    emoji: '🇫🇲',
    value: 'FM',
  },
  {
    label: 'Moldova',
    dial_value: '+373',
    emoji: '🇲🇩',
    value: 'MD',
  },
  {
    label: 'Monaco',
    dial_value: '+377',
    emoji: '🇲🇨',
    value: 'MC',
  },
  {
    label: 'Mongolia',
    dial_value: '+976',
    emoji: '🇲🇳',
    value: 'MN',
  },
  {
    label: 'Montenegro',
    dial_value: '+382',
    emoji: '🇲🇪',
    value: 'ME',
  },
  {
    label: 'Montserrat',
    dial_value: '+1664',
    emoji: '🇲🇸',
    value: 'MS',
  },
  {
    label: 'Morocco',
    dial_value: '+212',
    emoji: '🇲🇦',
    value: 'MA',
  },
  {
    label: 'Mozambique',
    dial_value: '+258',
    emoji: '🇲🇿',
    value: 'MZ',
  },
  {
    label: 'Myanmar',
    dial_value: '+95',
    emoji: '🇲🇲',
    value: 'MM',
  },
  {
    label: 'Namibia',
    emoji: '🇳🇦',
    dial_value: '+264',
    value: 'NA',
  },
  {
    label: 'Nauru',
    dial_value: '+674',
    emoji: '🇳🇷',
    value: 'NR',
  },
  {
    label: 'Nepal',
    dial_value: '+977',
    emoji: '🇳🇵',
    value: 'NP',
  },
  {
    label: 'Netherlands',
    dial_value: '+31',
    emoji: '🇳🇱',
    value: 'NL',
  },
  {
    label: 'Netherlands Antilles',
    dial_value: '+599',
    emoji: '🇧🇶',
    value: 'AN',
  },
  {
    label: 'New Caledonia',
    dial_value: '+687',
    emoji: '🇳🇨',
    value: 'NC',
  },
  {
    label: 'New Zealand',
    dial_value: '+64',
    emoji: '🇳🇿',
    value: 'NZ',
  },
  {
    label: 'Nicaragua',
    dial_value: '+505',
    emoji: '🇳🇮',
    value: 'NI',
  },
  {
    label: 'Niger',
    dial_value: '+227',
    emoji: '🇳🇪',
    value: 'NE',
  },
  {
    label: 'Nigeria',
    dial_value: '+234',
    emoji: '🇳🇬',
    value: 'NG',
  },
  {
    label: 'Niue',
    dial_value: '+683',
    emoji: '🇳🇺',
    value: 'NU',
  },
  {
    label: 'Norfolk Island',
    dial_value: '+672',
    emoji: '🇳🇫',
    value: 'NF',
  },
  {
    label: 'Northern Mariana Islands',
    dial_value: '+1670',
    emoji: '🇲🇵',
    value: 'MP',
  },
  {
    label: 'Norway',
    dial_value: '+47',
    emoji: '🇳🇴',
    value: 'NO',
  },
  {
    label: 'Oman',
    dial_value: '+968',
    emoji: '🇴🇲',
    value: 'OM',
  },
  {
    label: 'Pakistan',
    dial_value: '+92',
    emoji: '🇵🇰',
    value: 'PK',
  },
  {
    label: 'Palau',
    dial_value: '+680',
    emoji: '🇵🇼',
    value: 'PW',
  },
  {
    label: 'Palestinian Territories',
    dial_value: '+970',
    emoji: '🇵🇸',
    value: 'PS',
  },
  {
    label: 'Panama',
    dial_value: '+507',
    emoji: '🇵🇦',
    value: 'PA',
  },
  {
    label: 'Papua New Guinea',
    dial_value: '+675',
    emoji: '🇵🇬',
    value: 'PG',
  },
  {
    label: 'Paraguay',
    dial_value: '+595',
    emoji: '🇵🇾',
    value: 'PY',
  },
  {
    label: 'Peru',
    dial_value: '+51',
    emoji: '🇵🇪',
    value: 'PE',
  },
  {
    label: 'Philippines',
    dial_value: '+63',
    emoji: '🇵🇭',
    value: 'PH',
  },
  {
    label: 'Pitcairn Islands',
    dial_value: '+872',
    emoji: '🇵🇳',
    value: 'PN',
  },
  {
    label: 'Poland',
    dial_value: '+48',
    emoji: '🇵🇱',
    value: 'PL',
  },
  {
    label: 'Portugal',
    dial_value: '+351',
    emoji: '🇵🇹',
    value: 'PT',
  },
  {
    label: 'Puerto Rico',
    dial_value: '+1939',
    emoji: '🇵🇷',
    value: 'PR',
  },
  {
    label: 'Qatar',
    dial_value: '+974',
    emoji: '🇶🇦',
    value: 'QA',
  },
  {
    label: 'Romania',
    dial_value: '+40',
    emoji: '🇷🇴',
    value: 'RO',
  },
  {
    label: 'Russia',
    dial_value: '+7',
    emoji: '🇷🇺',
    value: 'RU',
  },
  {
    label: 'Rwanda',
    dial_value: '+250',
    emoji: '🇷🇼',
    value: 'RW',
  },
  {
    label: 'Reunion',
    dial_value: '+262',
    emoji: '🇷🇪',
    value: 'RE',
  },
  {
    label: 'Saint Barthelemy',
    dial_value: '+590',
    emoji: '🇧🇱',
    value: 'BL',
  },
  {
    label: 'Saint Helena',
    dial_value: '+290',
    emoji: '🇸🇭',
    value: 'SH',
  },
  {
    label: 'Saint Kitts & Nevis',
    dial_value: '+1869',
    emoji: '🇰🇳',
    value: 'KN',
  },
  {
    label: 'Saint Lucia',
    dial_value: '+1758',
    emoji: '🇱🇨',
    value: 'LC',
  },
  {
    label: 'Saint Martin',
    dial_value: '+590',
    emoji: '🇲🇫',
    value: 'MF',
  },
  {
    label: 'Saint Pierre & Miquelon',
    dial_value: '+508',
    emoji: '🇵🇲',
    value: 'PM',
  },
  {
    label: 'Saint Vincent & the Grenadines',
    dial_value: '+1784',
    emoji: '🇻🇨',
    value: 'VC',
  },
  {
    label: 'Samoa',
    dial_value: '+685',
    emoji: '🇼🇸',
    value: 'WS',
  },
  {
    label: 'San Marino',
    dial_value: '+378',
    emoji: '🇸🇲',
    value: 'SM',
  },
  {
    label: 'Sao Tome & Principe',
    dial_value: '+239',
    emoji: '🇸🇹',
    value: 'ST',
  },
  {
    label: 'Saudi Arabia',
    dial_value: '+966',
    emoji: '🇸🇦',
    value: 'SA',
  },
  {
    label: 'Senegal',
    dial_value: '+221',
    emoji: '🇸🇳',
    value: 'SN',
  },
  {
    label: 'Serbia',
    dial_value: '+381',
    emoji: '🇷🇸',
    value: 'RS',
  },
  {
    label: 'Seychelles',
    dial_value: '+248',
    emoji: '🇸🇨',
    value: 'SC',
  },
  {
    label: 'Sierra Leone',
    dial_value: '+232',
    emoji: '🇸🇱',
    value: 'SL',
  },
  {
    label: 'Singapore',
    dial_value: '+65',
    emoji: '🇸🇬',
    value: 'SG',
  },
  {
    label: 'Slovakia',
    dial_value: '+421',
    emoji: '🇸🇰',
    value: 'SK',
  },
  {
    label: 'Slovenia',
    dial_value: '+386',
    emoji: '🇸🇮',
    value: 'SI',
  },
  {
    label: 'Solomon Islands',
    dial_value: '+677',
    emoji: '🇸🇧',
    value: 'SB',
  },
  {
    label: 'Somalia',
    dial_value: '+252',
    emoji: '🇸🇴',
    value: 'SO',
  },
  {
    label: 'South Africa',
    dial_value: '+27',
    emoji: '🇿🇦',
    value: 'ZA',
  },
  {
    label: 'South Sudan',
    dial_value: '+211',
    emoji: '🇸🇸',
    value: 'SS',
  },
  {
    label: 'South Georgia & the South Sandwich Islands',
    dial_value: '+500',
    emoji: '🇬🇸',
    value: 'GS',
  },
  {
    label: 'Spain',
    dial_value: '+34',
    emoji: '🇪🇸',
    value: 'ES',
  },
  {
    label: 'Sri Lanka',
    dial_value: '+94',
    emoji: '🇱🇰',
    value: 'LK',
  },
  {
    label: 'Sudan',
    dial_value: '+249',
    emoji: '🇸🇩',
    value: 'SD',
  },
  {
    label: 'Suriname',
    dial_value: '+597',
    emoji: '🇸🇷',
    value: 'SR',
  },
  {
    label: 'Svalbard & Jan Mayen',
    dial_value: '+47',
    emoji: '🇸🇯',
    value: 'SJ',
  },
  {
    label: 'Swaziland',
    dial_value: '+268',
    emoji: '🇸🇿',
    value: 'SZ',
  },
  {
    label: 'Sweden',
    dial_value: '+46',
    emoji: '🇸🇪',
    value: 'SE',
  },
  {
    label: 'Switzerland',
    dial_value: '+41',
    emoji: '🇨🇭',
    value: 'CH',
  },
  {
    label: 'Syrian Arab Republic',
    dial_value: '+963',
    emoji: '🇸🇾',
    value: 'SY',
  },
  {
    label: 'Taiwan',
    dial_value: '+886',
    emoji: '🇹🇼',
    value: 'TW',
  },
  {
    label: 'Tajikistan',
    dial_value: '+992',
    emoji: '🇹🇯',
    value: 'TJ',
  },
  {
    label: 'Tanzania',
    dial_value: '+255',
    emoji: '🇹🇿',
    value: 'TZ',
  },
  {
    label: 'Thailand',
    dial_value: '+66',
    emoji: '🇹🇭',
    value: 'TH',
  },
  {
    label: 'Timor-Leste',
    dial_value: '+670',
    emoji: '🇹🇱',
    value: 'TL',
  },
  {
    label: 'Togo',
    dial_value: '+228',
    emoji: '🇹🇬',
    value: 'TG',
  },
  {
    label: 'Tokelau',
    dial_value: '+690',
    emoji: '🇹🇰',
    value: 'TK',
  },
  {
    label: 'Tonga',
    dial_value: '+676',
    emoji: '🇹🇴',
    value: 'TO',
  },
  {
    label: 'Trinidad & Tobago',
    dial_value: '+1868',
    emoji: '🇹🇹',
    value: 'TT',
  },
  {
    label: 'Tunisia',
    dial_value: '+216',
    emoji: '🇹🇳',
    value: 'TN',
  },
  {
    label: 'Türkiye',
    dial_value: '+90',
    emoji: '🇹🇷',
    value: 'TR',
  },
  {
    label: 'Turkmenistan',
    dial_value: '+993',
    emoji: '🇹🇲',
    value: 'TM',
  },
  {
    label: 'Turks & Caicos Islands',
    dial_value: '+1649',
    emoji: '🇹🇨',
    value: 'TC',
  },
  {
    label: 'Tuvalu',
    dial_value: '+688',
    emoji: '🇹🇻',
    value: 'TV',
  },
  {
    label: 'Uganda',
    dial_value: '+256',
    emoji: '🇺🇬',
    value: 'UG',
  },
  {
    label: 'Ukraine',
    dial_value: '+380',
    emoji: '🇺🇦',
    value: 'UA',
  },
  {
    label: 'United Arab Emirates',
    dial_value: '+971',
    emoji: '🇦🇪',
    value: 'AE',
  },
  {
    label: 'United Kingdom',
    dial_value: '+44',
    emoji: '🇬🇧',
    value: 'GB',
  },
  {
    label: 'United States',
    dial_value: '+1',
    emoji: '🇺🇸',
    value: 'US',
  },
  {
    label: 'Uruguay',
    dial_value: '+598',
    emoji: '🇺🇾',
    value: 'UY',
  },
  {
    label: 'Uzbekistan',
    dial_value: '+998',
    emoji: '🇺🇿',
    value: 'UZ',
  },
  {
    label: 'Vanuatu',
    dial_value: '+678',
    emoji: '🇻🇺',
    value: 'VU',
  },
  {
    label: 'Venezuela',
    dial_value: '+58',
    emoji: '🇻🇪',
    value: 'VE',
  },
  {
    label: 'Vietnam',
    dial_value: '+84',
    emoji: '🇻🇳',
    value: 'VN',
  },
  {
    label: 'Virgin Islands, British',
    dial_value: '+1284',
    emoji: '🇻🇬',
    value: 'VG',
  },
  {
    label: 'Virgin Islands, U.S.',
    dial_value: '+1340',
    emoji: '🇻🇮',
    value: 'VI',
  },
  {
    label: 'Wallis & Futuna',
    dial_value: '+681',
    emoji: '🇼🇫',
    value: 'WF',
  },
  {
    label: 'Yemen',
    dial_value: '+967',
    emoji: '🇾🇪',
    value: 'YE',
  },
  {
    label: 'Zambia',
    dial_value: '+260',
    emoji: '🇿🇲',
    value: 'ZM',
  },
  {
    label: 'Zimbabwe',
    dial_value: '+263',
    emoji: '🇿🇼',
    value: 'ZW',
  },
]
